// packages/breadcrumb/src/components/breadcrumb/breadcrumb.tsx
import { Component, Prop, h } from '@stencil/core';

@Component({
  tag: 'ip-breadcrumb',
  styleUrl: 'breadcrumb.scss',
  shadow: true,
})
export class BreadcrumbComponent {
  @Prop() breadcrumbTitle: string = '';
  @Prop() breadcrumbItems: string = '[]';
  @Prop() prefixAriaLabel: string = 'Link to';
  @Prop() separatorIcon: string = '>';

  private parseBreadcrumbItems() {
    try {
      return JSON.parse(this.breadcrumbItems);
    } catch (e) {
      console.error(
        'Invalid JSON string for breadcrumbItems:',
        this.breadcrumbItems,
      );
      return [];
    }
  }

  private handleKeydown(event: KeyboardEvent, link?: string) {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      if (link) {
        window.location.href = link;
      }
    }
  }

  render() {
    const items = this.parseBreadcrumbItems();
    return (
      <div class="wrapper-title">
        {this.breadcrumbTitle && <h1>{this.breadcrumbTitle}</h1>}
        <nav class="breadcrumb" aria-label="Breadcrumb">
          <ol class="breadcrumb">
            {items.map((item, index) => {
              const isLast = index === items.length - 1;
              return (
                <li
                  class={{ 'breadcrumb-item': true, active: isLast }}
                  aria-current={isLast ? 'page' : undefined}
                  role={isLast ? 'none' : 'listitem'}
                >
                  {!isLast ? (
                    <a
                      href={item.link}
                      onKeyDown={(event) =>
                        this.handleKeydown(event, item.link)
                      }
                      aria-label={`${this.prefixAriaLabel} ${item.label}`}
                      role="link"
                    >
                      {item.label}
                    </a>
                  ) : (
                    <span>{item.label}</span>
                  )}
                  {!isLast && (
                    <span class="icon" innerHTML={this.separatorIcon}></span>
                  )}
                </li>
              );
            })}
          </ol>
        </nav>
      </div>
    );
  }
}

// apps/demo/src/app/features/breadcrumb/breadcrumb.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-breadcrumb',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './breadcrumb.component.html',
  styleUrl: './breadcrumb.component.scss',
})
export class BreadcrumbComponent {
  @Input() title: string = '';
  @Input() breadcrumbItems: Array<{ label: string; link?: string }> = [];

  handleKeydown(event: KeyboardEvent, link?: string): void {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      if (link) {
        window.location.href = link;
      }
    }
  }
}

<div class="wrapper-title">
  <h1>{{ title }}</h1>
  <nav class="breadcrumb" aria-label="Breadcrumb">
    <ol class="breadcrumb">
      <ng-container *ngFor="let item of breadcrumbItems; let last = last">
        <li
          class="breadcrumb-item"
          [ngClass]="{ active: last }"
          [attr.aria-current]="last ? 'page' : null"
          (keydown)="handleKeydown($event, item.link)"
        >
          <ng-container *ngIf="!last; else lastBreadcrumb">
            <a
              [routerLink]="item.link"
              (keydown)="handleKeydown($event, item.link)"
              [attr.aria-label]="'Link to ' + item.label"
              >{{ item.label }}</a
            >
          </ng-container>
          <ng-template #lastBreadcrumb>
            {{ item.label }}
          </ng-template>
        </li>
        <ng-container class="icon" *ngIf="!last">&gt;</ng-container>
      </ng-container>
    </ol>
  </nav>
</div>
